<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <Nullable>enable</Nullable>
        <LangVersion>10</LangVersion>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SodaFlow.Samples.Search.ViewModels\SodaFlow.Samples.Search.ViewModels.csproj"/>
    </ItemGroup>

</Project>
