<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <AssemblyName>SodaFlow.Tests.Internal</AssemblyName>
        <RootNamespace>SodaFlow.Tests.Internal</RootNamespace>
        <EnableDefaultItems>false</EnableDefaultItems>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1"/>
        <PackageReference Include="NUnit" Version="3.11.0"/>
        <PackageReference Include="NUnit3TestAdapter" Version="3.10.0"/>
        <PackageReference Include="System.ValueTuple" Version="4.4.0"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="CalmTests.cs"/>
        <Compile Include="CellTests.cs"/>
        <Compile Include="NodeTests.cs"/>
        <Compile Include="TransactionTests.cs"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\SodaFlow.Core\SodaFlow.Core.csproj"/>
        <ProjectReference Include="..\SodaFlow\SodaFlow.csproj"/>
        <ProjectReference Include="..\SodaFlow.Functional\SodaFlow.Functional.csproj"/>
    </ItemGroup>

</Project>
